# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0af894148040bef39ab8201315ff1835b50e3ba8460956479c1d0c0c557e13b4b3b2e2959292e06b41a82764758cf8b813df0ad0e37c35215f359a7fa04b37b3

test:
  secret_key_base: 6bdd13abd4e1964d6c9ff23936dd55e25b9f2bd92069d1528646d87ce31d432646962905686f2cbee15602e3fd1b4b5cf1f61d8802b37e54016953a574f40f74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
